global_options:
  freezed:
    runs_before:
      - json_serializable

targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: swaggers/
          input_urls:
            - url: "https://raw.githubusercontent.com/Kareadita/Kavita/refs/tags/v0.8.9/openapi.json"
          output_folder: "lib/api"
