default_platform(:ios)

platform :ios do
  private_lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_KEY'],
      is_key_content_base64: false,
      in_house: false
    )
  end

  desc 'Build iOS app for TestFlight'
  lane :build do |options|
    version = options[:version]
    build_number = options[:build_number]

    increment_version_number(
      version_number: version,
      xcodeproj: 'Runner.xcodeproj'
    )

    increment_build_number(
      build_number: build_number,
      xcodeproj: 'Runner.xcodeproj'
    )

    build_app(
      workspace: 'Runner.xcworkspace',
      scheme: 'Runner',
      export_method: 'app-store',
      export_options: {
        provisioningProfiles: lane_context[:MATCH_PROVISIONING_PROFILE_MAPPING]
      }
    )
  end

  desc 'Build and upload to TestFlight'
  lane :beta do |options|
    version = options[:version]
    build_number = options[:build_number]

    setup_ci

    match(
      type: 'appstore'
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: 'Runner.xcodeproj',
      code_sign_identity: 'Apple Distribution',
      profile_name: lane_context[:MATCH_PROVISIONING_PROFILE_MAPPING]['com.rodonisi.fluvita']
    )

    build(
      version: version,
      build_number: build_number
    )

    load_asc_api_key
    upload_to_testflight(
      api_key: lane_context[SharedValues::APP_STORE_CONNECT_API_KEY],
      skip_waiting_for_build_processing: true
    )
  end
end
